package tad.entity;

import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.MapsId;
import javax.persistence.Table;

/**
 * OrderDetail generated by hbm2java
 */
@Entity
@Table(name = "OrderDetail", schema = "dbo", catalog = "FashionShop")
public class OrderDetail {

	@EmbeddedId
	private OrderDetailId id;

	@ManyToOne(fetch = FetchType.EAGER)
	@MapsId("orderId")
	@JoinColumn(name = "OrderID", nullable = false, insertable = false, updatable = false)
	private Orders order;

	@ManyToOne(fetch = FetchType.EAGER)
	@MapsId("productId")
	@JoinColumn(name = "ProductID", nullable = false, insertable = false, updatable = false)
	private Product product;
	
	@ManyToOne(fetch = FetchType.EAGER)
	@MapsId("sizeId")
	@JoinColumn(name = "SizeID", nullable = false, insertable = false, updatable = false)
	private Size size;

	@Column(name = "Quantity", nullable = false)
	private int quantity;

	@Column(name = "Coupon")
	private double coupon;
	
	@Column(name = "Price", nullable = false)
	private Double price;
	
	public double getPrice() {
		return price;
	}

	public double getCoupon() {
		return coupon;
	}

	public void setCoupon(double d) {
		this.coupon = d;
	}

	public OrderDetail(OrderDetailId id, Orders order, Product product, int quantity,Size size,Double price) {
		this.id = id;
		this.order = order;
		this.product = product;
		this.quantity = quantity;
		this.size = size;
		this.price = price;
	}
	
	

	public OrderDetail() {

	}

	public OrderDetailId getId() {
		return this.id;
	}

	public void setId(OrderDetailId id) {
		this.id = id;
	}

	public Orders getOrder() {
		return this.order;
	}

	public void setOrder(Orders order) {
		this.order = order;
	}

	public Product getProduct() {
		return this.product;
	}

	public void setProduct(Product product) {
		this.product = product;
	}

	public int getQuantity() {
		return quantity;
	}

	public void setQuantity(int quantity) {
		this.quantity = quantity;
	}

	public Size getSize() {
		return size;
	}

	public void setSize(Size size) {
		this.size = size;
	}

	public void setPrice(Double double1) {
		this.price = double1;
	}
	

}
